# Tags: 4.8-20211109-windowsservercore-ltsc2019, 4.8-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-20211109-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
