# Tags: 3.5-20211109-windowsservercore-2004, 3.5-windowsservercore-2004, 4.8-3.5-windowsservercore-2004
FROM mcr.microsoft.com/dotnet/framework/runtime:3.5-20211109-windowsservercore-2004
FROM mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-2004
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-3.5-windowsservercore-2004
