# Tags: 4.8-windowsservercore-20H2
FROM dotnet/framework/runtime:4.8-windowsservercore-20H2
FROM dotnet/framework/runtime:4.8-20211109-windowsservercore-20H2
FROM dotnet/framework/runtime:4.8-windowsservercore-2009
